### ISSUE TITLE
Data loss in case of parallel snapshot during writing data

### ISSUE THREAD

**Issue by tmenjo** [sheepdog/sheepdog#331] opened 2016-11-02 07:20 UTC
This may be because of rather more complicated one than race condition among writing data to object and parallel and multiple 'dog vdi snapshot' (one is to be snapshot, the others rollback unintentionally).

See also #330.

## Steps to reproduce:
1. Create VDI *A*
2. Start to repeat two 'dog vdi snapshot *A*' in parallel
3. Loop 'dog vdi write *A*' then 'dog vdi read *A*' to verify whether I can read the same data as the written

## Expected behavior
In every loop, I should read the **same** data as the written.

## Actual behavior
Eventually, I read data that is **different** from the written. Moreover, **I cannot find the written data in any of snapshots or working VDI**.

I run the reproduction script (mentioned later) and got below. This tells me that not only I could not read the same data as the written but also I really lost the written data.

```
_0_1_2_____3_4________5__6_6 ! 7
00000010112122222222223233334344444444444444444454555555656666666[6]
```

The first line shows the history of write and read. Here, each number is the result of read after write, underscore means retry because of SD_RES_READONLY and "6 ! 7" shows that **dog wrote "7"** but read "6".

The second line shows the content of each snapshot (bare number) and working VDI (number in bracket). I said that dog wrote "7" but **there is no "7"**. Even if there is unintended rollback, "7" should remain in any of snapshots or working VDI.

## Reproduction script
```sh
#!/bin/bash
export LANG=C LC_ALL=C
set -ue

function loop_snapshot
{
	local vdiname="$1"
	while :; do
		dog vdi snapshot "$vdiname" &\
		dog vdi snapshot "$vdiname"
	done
}

### main ###
sheep --version
sudo sysctl -w fs.nr_open=6144000 >/dev/null

sudo pkill sheep ||:
while pgrep sheep >/dev/null ; do sleep 1 ; done
sudo rm -rf /tmp/0
mkdir -p /tmp/0
sudo sheep -l level=debug /tmp/0
while ! [ -f /tmp/0/sheep.log ] ; do sleep 1 ; done
while ! grep daemon /tmp/0/sheep.log >/dev/null ; do sleep 1 ; done
dog cluster format -c 1 >/dev/null
dog vdi create test_vdi01 1G
echo -n 0 | dog vdi write test_vdi01 0 1

loop_snapshot test_vdi01 &
cpid="$!"

i=0
while :; do
	if ! ( echo -n "$i" | dog vdi write test_vdi01 2>/dev/null ) ; then
		echo -n '_'
		continue
	fi
	j=$(dog vdi read test_vdi01 0 1)
	echo -n "$j"
	if [ "$i" != "$j" ] ; then
		echo -n " ! $i"
		break
	fi
	i=$(((i+1)%10))
done
echo
kill "$cpid"
wait "$cpid" 2>/dev/null ||:

dog vdi list -r | grep '^s' | awk '{print $3;}' |\
xargs -i dog vdi read -s {} test_vdi01 0 1
echo -n '['
dog vdi read test_vdi01 0 1
echo ']'
sudo grep -vE 'INFO|DEBUG' /tmp/0/sheep.log
```

**Comment by mitake** [comment] 2017-01-20 05:41
This problem cannot be solved because there is no way of serializing snapshot request (issued by dog and result a cluster request that involves corosync or zookeeper) and ordinal write request (issued by VMs or iSCSI initiators and only handled by sheep processes). If we can serialize them, the inconsistent state can be hidden from each other (dog and VMs + iSCSI initiators) but it requires a centralized metadata server that handles every write and snapshot request. It will be a bottleneck of performance and cannot coexist with the original design of sheepdog.

However, this problem isn't realistic in real deployments. It is because fsfreeze and cache flushing are required for taking a consistent snapshot (if I remember correctly, qemu-ga does this role). So the interleaving of snapshot request and write request won't be happen under correct operation.

**Comment by tristanball** [comment] 2017-03-31 23:59
I've managed environments where this would be a serious issue:

- Flush and Freeze operations themselves can take a long time, even to the point of timing out, or having end user visible delays. However, so long as the storage layer honors things like O_SYNC, flush requests etc, snapshots are atomic for an entire virtual disk and the guest filesystem and app have their own recovery mechanisms (eg, database journaling) - then snapshots without a freeze generally work OK, but recovering from these snapshots might take longer as there was more data in flight (journaled, but not yet written anywhere else)
- Not every VM can run a guest agent, eg guest OS is too old, too new, or a locked down vendor appliance.

I'd also argue that while it's OK for a snapshot to fail, or to be very occasionally unrecoverable, it's never OK for an acked write to the head/current disk to be lost - and that appears to be what's happening here?

Is this reproducible if only a single snapshot is occurring? I would think having multiple snapshots being taken at the same time is an unusual requirement, and the snapshots themselves could be serialized..

**Comment by mitake** [comment] 2017-04-06 02:13
@tristanball as you pointed out, the snapshot feature will be problematic for such a use case. However, typical RDBMSes provide the same functionality that don't rely on file systems or block devices. So how about just using it?

The snapshot functionality at block device layer is a relatively new afterthought (posix doesn't say anything about it). Unix applications are not aware about it and using it in a completely transparent manner is impossible...

**Comment by tristanball** [comment] 2017-04-06 04:12
My concern wasn't actually with the snapshotted data - but from my reading of the test case code above, it's possible to lose writes to the current vdi - ie, a 'vdi dog read' immediately following a 'vdi dog write' might not return the data that was just written. And from what @tmenjo  said, the written data isn't in the snapshot either - which is bad, but it's the loss of the write to the current VDI that scares me most.

Or have I misunderstood the issue?

I found anything that says whether a 'vdi dog write' uses async to sync style behaviour, but even if it was async, the only time I'd expect to see inconsistent data from the same client os instance would be if there was some kind of fault.

@tmenjo  - Did you realise that your loop_snapshot function is almost certainly going to be running more than two snapshots it parallel? If the first snap is still running when the second completes, the next loop will add another to the background, and so on...

A quick rewrite of the script to use 'dd' in place of vdi read/write and 'btrfs' snapshots on my local machine can't reproduce this error.

**Comment by vtolstov** [comment] 2017-12-19 12:48
And so, how to fix this problem?

**Comment by vtolstov** [comment] 2017-12-19 12:50
If i do snapshot from qemu side, does i have such issue or not?

**Comment by mitake** [comment] 2017-12-22 04:53
The realistic use case of taking snapshot must have fsfreeze. Let's close this.

**Comment by mitake** [comment] 2017-12-22 04:53
@vtolstov just doing fsfreeze is ok for this probelm

**Closed by mitake** 2017-12-22 04:53 UTC

**Comment by vtolstov** [comment] 2017-12-22 10:25
please, reopen. this is not suitable for me (because some os does not have guest agent at all (freebsd, and such) also guest agent may not respond.
And as i understand this issue this broke user data that written while i do snapshot, i don't think that some functionality of sheepdog needs to be depend on guest os or guest software.

**Comment by mitake** [comment] 2017-12-25 04:38
Do you have any idea for solving it without having the mechanisms like guest agent? I don't know storage systems including proprietary things which can support completely transparent snapshot creation. Probably it is impossible.

**Comment by vtolstov** [comment] 2017-12-25 08:13
I dont say about consistent inside guest, but i say about that fact that everything that written needs to be reading after that.
As i see in this issue, data that written via dog vdi write does not read back. So we silently loose data and don't know about that fact.
Why we can't serialize snapshot and write request if we do that via qemu qmp ?
I think that if we work outside of qemu while vm is running this is may not be fixed, because we don't know about fact that vdi is used for writing.
But if we do snapshot via qemu as i understand we can guarantee fact that write for this vdi follows only when we have successful/failure snapshot  response.
